"""Versioned FPL scoring values for the 2026/27 V1 ruleset."""

from .enums import Position

SCORING_RULESET_VERSION = "2026_27_v1"
PROBABILITY_TOLERANCE = 1e-8
TAIL_PROBABILITY_TOLERANCE = 1e-12
APPEARANCE_UNDER_60 = 1
APPEARANCE_60_PLUS = 2
GOAL_POINTS = {Position.GK: 10, Position.DEF: 6, Position.MID: 5, Position.FWD: 4}
ASSIST_POINTS = 3
CLEAN_SHEET_POINTS = {Position.GK: 4, Position.DEF: 4, Position.MID: 1, Position.FWD: 0}
SAVE_INTERVAL = 3
SAVE_POINTS_PER_INTERVAL = 1
PENALTY_SAVE_POINTS = 5
DEFENDER_DC_THRESHOLD = 10
MID_FWD_DC_THRESHOLD = 12
DC_POINTS = 2
YELLOW_CARD_DEDUCTION = 1
RED_CARD_DEDUCTION = 3
OWN_GOAL_DEDUCTION = 2
PENALTY_MISS_DEDUCTION = 2
GOALS_CONCEDED_INTERVAL = 2
GOALS_CONCEDED_DEDUCTION = 1
